"""cards table

Revision ID: 0737052276db
Revises: e018e0ea78c2
Create Date: 2019-06-20 18:21:10.358758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0737052276db'
down_revision = 'e018e0ea78c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'card', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='unique')
    # ### end Alembic commands ###
