"""cards table

Revision ID: 158b05da423c
Revises: 
Create Date: 2019-06-18 12:54:43.325618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158b05da423c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_name'), 'card', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_name'), table_name='card')
    op.drop_table('card')
    # ### end Alembic commands ###
