"""cards table

Revision ID: c580e726f3c9
Revises: 
Create Date: 2019-06-20 16:04:41.003854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c580e726f3c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('api_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('layout', sa.String(length=300), nullable=True),
    sa.Column('scryfall_uri', sa.String(length=300), nullable=True),
    sa.Column('cmc', sa.Float(), nullable=True),
    sa.Column('type_line', sa.String(length=300), nullable=True),
    sa.Column('oracle_text', sa.String(length=300), nullable=True),
    sa.Column('mana_cost', sa.String(length=300), nullable=True),
    sa.Column('multiverse_ids', sa.PickleType(), nullable=True),
    sa.Column('power', sa.String(length=300), nullable=True),
    sa.Column('toughness', sa.String(length=300), nullable=True),
    sa.Column('loyalty', sa.String(length=300), nullable=True),
    sa.Column('life_modifier', sa.String(length=300), nullable=True),
    sa.Column('hand_modifier', sa.String(length=300), nullable=True),
    sa.Column('colors', sa.PickleType(), nullable=True),
    sa.Column('color_indicator', sa.PickleType(), nullable=True),
    sa.Column('color_identity', sa.PickleType(), nullable=True),
    sa.Column('all_parts', sa.PickleType(), nullable=True),
    sa.Column('card_faces', sa.PickleType(), nullable=True),
    sa.Column('legalities', sa.PickleType(), nullable=True),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.Column('foil', sa.Boolean(), nullable=True),
    sa.Column('nonfoil', sa.Boolean(), nullable=True),
    sa.Column('oversized', sa.Boolean(), nullable=True),
    sa.Column('edhrec_rank', sa.Float(), nullable=True),
    sa.Column('set', sa.String(length=300), nullable=True),
    sa.Column('set_name', sa.String(length=300), nullable=True),
    sa.Column('collector_number', sa.String(length=300), nullable=True),
    sa.Column('highres_image', sa.Boolean(), nullable=True),
    sa.Column('printed_name', sa.String(length=300), nullable=True),
    sa.Column('printed_type_line', sa.String(length=300), nullable=True),
    sa.Column('printed_text', sa.String(length=300), nullable=True),
    sa.Column('reprint', sa.Boolean(), nullable=True),
    sa.Column('digital', sa.Boolean(), nullable=True),
    sa.Column('rarity', sa.String(length=300), nullable=True),
    sa.Column('flavor_text', sa.String(length=300), nullable=True),
    sa.Column('artist', sa.String(length=300), nullable=True),
    sa.Column('illustration_id', sa.String(length=300), nullable=True),
    sa.Column('frame', sa.String(length=300), nullable=True),
    sa.Column('full_art', sa.Boolean(), nullable=True),
    sa.Column('watermark', sa.String(length=300), nullable=True),
    sa.Column('border_color', sa.String(length=300), nullable=True),
    sa.Column('story_spotlight_number', sa.Float(), nullable=True),
    sa.Column('timeshifted', sa.Boolean(), nullable=True),
    sa.Column('colorshifted', sa.Boolean(), nullable=True),
    sa.Column('futureshifted', sa.Boolean(), nullable=True),
    sa.Column('lang', sa.String(length=300), nullable=True),
    sa.Column('set_search_uri', sa.String(length=300), nullable=True),
    sa.Column('scryfall_set_uri', sa.String(length=300), nullable=True),
    sa.Column('image_uris', sa.PickleType(), nullable=True),
    sa.Column('uri', sa.String(length=300), nullable=True),
    sa.Column('spotlight_uri', sa.String(length=300), nullable=True),
    sa.Column('prices', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('api_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
