"""cards table

Revision ID: e018e0ea78c2
Revises: eee812980f6a
Create Date: 2019-06-20 17:04:01.544303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e018e0ea78c2'
down_revision = 'eee812980f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('story_spotlight_uri', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'story_spotlight_uri')
    # ### end Alembic commands ###
