"""cards table

Revision ID: eee812980f6a
Revises: c580e726f3c9
Create Date: 2019-06-20 17:02:17.102067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee812980f6a'
down_revision = 'c580e726f3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('purchase_uris', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'purchase_uris')
    # ### end Alembic commands ###
