"""empty message

Revision ID: 080c7f3622f6
Revises: bbe1e1ed431e
Create Date: 2019-08-20 11:58:10.043657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080c7f3622f6'
down_revision = 'bbe1e1ed431e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blacklist_token')
    # ### end Alembic commands ###
