"""empty message

Revision ID: bbe1e1ed431e
Revises: 8a46d06e78dd
Create Date: 2019-08-19 11:37:33.874180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe1e1ed431e'
down_revision = '8a46d06e78dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('deck',
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.api_id'], ),
    sa.PrimaryKeyConstraint('api_id')
    )
    op.create_table('deck_card_association_table',
    sa.Column('deck_api_id', sa.Integer(), nullable=True),
    sa.Column('card_api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_api_id'], ['card.api_id'], ),
    sa.ForeignKeyConstraint(['deck_api_id'], ['deck.api_id'], )
    )
    op.create_table('sideboard_card_association_table',
    sa.Column('deck_api_id', sa.Integer(), nullable=True),
    sa.Column('card_api_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_api_id'], ['card.api_id'], ),
    sa.ForeignKeyConstraint(['deck_api_id'], ['deck.api_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sideboard_card_association_table')
    op.drop_table('deck_card_association_table')
    op.drop_table('deck')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
